# Generated by Django 3.2.14 on 2024-10-27 20:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circulacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('responsavel', models.CharField(max_length=255, null=True, verbose_name='Responsável')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('previsao_devolucao', models.DateTimeField(verbose_name='Previsão Devolução')),
                ('data_baixa', models.DateTimeField(blank=True, null=True, verbose_name='Data de baixa')),
                ('situacao', models.CharField(choices=[('ABERTO', 'Aberto'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('TRANSFERIDO', 'Transferido')], default='ABERTO', max_length=50)),
                ('obs', models.TextField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Circulação de Equipamento',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('identificador', models.CharField(max_length=100, null=True, unique=True, verbose_name='Código')),
                ('serie', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nº Série')),
                ('obs_inventario', models.TextField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('AVARIADO', 'Avariado'), ('EXTRAVIO', 'Extravio'), ('DISPONIVEL', 'Disponível'), ('MANUTENCAO', 'Em Manutenção'), ('EM_CIRCULACAO', 'Em Circulação')], default='DISPONIVEL', max_length=50)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('equipamento__descricao',),
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('descricao', models.CharField(max_length=100, null=True, unique=True, verbose_name='Descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCirculacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('situacao', models.CharField(choices=[('DEVOLVIDO_AVARIA', 'Devolvido com avaria'), ('BAIXADO_NORMAL', 'Baixado Normal'), ('EM_CIRCULACAO', 'Em circulação'), ('EXTRAVIADO', 'Extravio'), ('CIRCULACAO_CANCELADA', 'Cancelado')], default='EM_CIRCULACAO', max_length=50)),
                ('obs', models.TextField(blank=True, null=True)),
                ('devolvido_em', models.DateTimeField(blank=True, null=True, verbose_name='devolvido em')),
            ],
            options={
                'verbose_name': 'Item de Circulação',
                'verbose_name_plural': 'Itens de Circulação',
                'ordering': ('-circulacao__created_at', 'circulacao__id', 'dispositivo__identificador'),
            },
        ),
        migrations.CreateModel(
            name='LocalUso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('descricao', models.CharField(max_length=100, null=True, unique=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Local de Uso',
                'verbose_name_plural': 'Locais de Uso',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='LogCirculacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('situacao', models.CharField(choices=[('ABERTO', 'Aberto'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('TRANSFERIDO', 'Transferido')], max_length=50)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log de Circulação',
                'verbose_name_plural': 'Logs de Circulação',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LogDispositivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('situacao', models.CharField(choices=[('AVARIADO', 'Avariado'), ('EXTRAVIO', 'Extravio'), ('DISPONIVEL', 'Disponível'), ('MANUTENCAO', 'Em Manutenção'), ('EM_CIRCULACAO', 'Em Circulação')], max_length=50, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StatusDispositivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('descricao', models.CharField(max_length=100, null=True, unique=True, verbose_name='Descrição')),
                ('permite_circular', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, default='#dddd', max_length=100, null=True, verbose_name='Cor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
