# Generated by Django 3.2.14 on 2024-10-27 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('nome', models.CharField(max_length=100, null=True, unique=True, verbose_name='Sistema')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wiki_categoriasistema_created_by_related', related_query_name='wiki_categoriasistemas_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wiki_categoriasistema_updated_by_related', related_query_name='wiki_categoriasistemas_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título')),
                ('text', models.TextField(blank=True, null=True)),
                ('html', models.TextField(blank=True, null=True)),
                ('corpo', django_quill.fields.QuillField(null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wiki_wiki_created_by_related', related_query_name='wiki_wikis_created_by', to=settings.AUTH_USER_MODEL)),
                ('membros', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('sistema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wiki.categoriasistema')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wiki_wiki_updated_by_related', related_query_name='wiki_wikis_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wiki',
                'verbose_name_plural': 'Wikis',
            },
        ),
    ]
