# Generated by Django 3.2.14 on 2024-10-27 20:36

import base.models
from django.db import migrations, models
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='arquivos', verbose_name='Arquivos')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('description', models.CharField(default='Configuração global padrão', max_length=100, null=True, verbose_name='Descrição')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[100, 100], upload_to=base.models.path_logo, verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Sistema - Configuração global',
                'verbose_name_plural': 'Sistema - Configurações globais',
                'permissions': (('can_resetpassword_global', 'Redefinir senha Global'), ('can_gerenciar_containers', 'Pode Gerenciar Containers na Infraestrutura')),
            },
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(verbose_name='Log')),
                ('path', models.TextField(verbose_name='Path')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sistema - Log de Sistema',
                'verbose_name_plural': 'Sistema - Logs de Sistema',
            },
        ),
        migrations.CreateModel(
            name='MonitorServico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('servico', models.CharField(max_length=250, null=True, verbose_name='Serviço')),
                ('url', models.CharField(max_length=250, null=True, verbose_name='URL')),
                ('referencia', models.CharField(blank=True, max_length=250, null=True, verbose_name='Referência')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Monitor - Teste de Serviço',
                'verbose_name_plural': 'Monitor - Teste de Serviços',
            },
        ),
        migrations.CreateModel(
            name='SystemParams',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('chave', models.CharField(max_length=80, null=True, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Sistema - Parâmetro',
                'verbose_name_plural': 'Sistema - Parâmetros',
            },
        ),
        migrations.CreateModel(
            name='TeamsChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('titulo', models.CharField(max_length=255, null=True, verbose_name='Título do canal')),
                ('webhook', models.URLField(max_length=255, null=True, unique=True, verbose_name='Webhook')),
                ('ativo', models.BooleanField(default=True, help_text='Canal está ativo para envio?')),
            ],
            options={
                'verbose_name': 'Teams - Canal',
                'verbose_name_plural': 'Teams - Canais',
            },
        ),
    ]
