# Generated by Django 3.2.14 on 2024-10-27 20:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cofre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('descricao', models.CharField(max_length=254, null=True, verbose_name='Descrição')),
                ('hostname', models.CharField(blank=True, max_length=254, null=True, verbose_name='Hostname')),
                ('ip', models.CharField(blank=True, max_length=254, null=True, verbose_name='IP')),
                ('url', models.CharField(blank=True, max_length=254, null=True, verbose_name='Url')),
                ('usuario', models.CharField(max_length=254, null=True, verbose_name='Usuário')),
                ('senha', models.CharField(help_text='Altere este campo somente se desejar alterar a senha. O campo é criptografado após salvar.', max_length=254, null=True, verbose_name='Senha')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('exibir', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Registro de Cofre',
                'verbose_name_plural': 'Registros de Cofre',
                'permissions': (('cofre_infraestrutura', 'Acessar Cofre Infraestrutura'), ('cofre_desenvolvimento', 'Acessar Cofre Desenvolvimento'), ('cofre_master', 'Acessar Cofre Integral')),
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('descricao', models.CharField(max_length=254, null=True, unique=True, verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('descricao', models.CharField(max_length=254, null=True, unique=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
    ]
