# Generated by Django 3.2.14 on 2024-10-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('numero_local', models.CharField(max_length=50, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('senha', models.IntegerField(help_text='Sequência de senha do dia/serviço', null=True)),
                ('data_chegada', models.DateTimeField(blank=True, help_text='Data/Hora definida no ato da triagem da senha', null=True, verbose_name='Chegada')),
                ('data_chamada', models.DateTimeField(blank=True, help_text='Data/Hora definida no ato da chamada de senha no Painel', null=True, verbose_name='Chamada')),
                ('data_inicio', models.DateTimeField(blank=True, help_text='Data/Hora definida no ato do início do atendimento', null=True, verbose_name='Início')),
                ('data_fim', models.DateTimeField(blank=True, help_text='Data/Hora definida no ato do encerramento do atendimento', null=True, verbose_name='Encerramento')),
                ('tempo_espera', models.IntegerField(blank=True, default=None, help_text='Tempo de espera em segundos', null=True, verbose_name='Espera')),
                ('tempo_deslocamento', models.IntegerField(blank=True, default=None, help_text='Tempo entre a chamada de senha no painel e início do atendimento', null=True, verbose_name='Deslocamento')),
                ('tempo_atendimento', models.IntegerField(blank=True, default=None, help_text='Tempo entre o início e o encerramento do atendimento', null=True)),
                ('tempo_permanencia', models.IntegerField(blank=True, default=None, help_text='Tempo total desde a triagem de senha até o tempo de encerramento', null=True, verbose_name='Permanência')),
                ('avaliacao', models.IntegerField(blank=True, default=None, help_text='Nota de avaliação do atendimento', null=True, verbose_name='Nota')),
                ('status_atendimento', models.CharField(choices=[('iniciado', 'Iniciado'), ('encerrado', 'Encerrado'), ('nao_compareceu', 'Não Compareceu'), ('chamado', 'Chamado'), ('emitido', 'Emitido'), ('transferido', 'Transferido')], default='emitido', help_text='Status atual do atendimento', max_length=50, null=True, verbose_name='Status')),
                ('sigla_senha', models.CharField(max_length=50, null=True)),
                ('resolucao', models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('resolvido', 'Resolvido')], default=None, help_text='Estado de Resolução do atendimento', max_length=50, null=True, verbose_name='Resolução')),
                ('obs', models.TextField(blank=True, help_text='Informações adicionais sobre o atendimento além das observações comentadas', null=True, verbose_name='Observação')),
                ('historico', models.BooleanField(default=False, help_text='Os Atendimentos são definidos como históricos quando foram finalizados como encerrados ou não comparecidos do dia anterior. Para os demais atendimentos(do dia anterior), é necessário encerrá-los', verbose_name='Histórico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AtendimentoComentario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('comentario', models.TextField(max_length=5000)),
            ],
            options={
                'verbose_name': 'Comentário de Atendimento',
                'verbose_name_plural': 'Comentários de Atendimento',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('matricula', models.CharField(blank=True, max_length=20, null=True)),
                ('nome', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('celular', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PainelSenha',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('pode_atender', models.BooleanField(default=False)),
                ('acessa_triagem', models.BooleanField(default=False)),
                ('acessa_painel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, null=True)),
                ('peso', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, null=True)),
                ('sigla', models.CharField(max_length=4, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='alterado em')),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
